resources:
# https://docs.projectcalico.org/manifests/calico.yaml
- calico.yaml

patchesStrategicMerge:
# adds
# "container_settings": {
#   "allow_ip_forwarding": true
# }
- allow_ip_forwarding_patch.yaml
